export const lianzhuCopy = {
  zh: ['连珠馆', '一间随时入座的网上棋馆。三至七连珠，自定规则；黑白弹棋，凭手感出招。可以邀朋友同桌对弈，也可以请新手、棋士或国手三档棋魂陪练。无需下载，打开即玩。', '连珠馆：木桌上的黑白棋子与暖灯', '网页 · 手机与电脑', '现已开放', '进入棋馆'],
  'zh-Hant': ['連珠館', '一間隨時入座的網上棋館。三至七連珠，自訂規則；黑白彈棋，憑手感出招。可以邀朋友同桌對弈，也可以請新手、棋士或國手三種難度的棋魂陪練。無需下載，打開即玩。', '連珠館：木桌上的黑白棋子與暖燈', '網頁 · 手機與電腦', '現已開放', '進入棋館'],
  en: ['Lianzhu', 'Take a seat in an online game hall. Choose three to seven in a row, or flick black and white pieces across the board in Tanqi. Invite a friend or practise against an AI opponent at one of three difficulty levels. Play in your browser, with no download needed.', 'Lianzhu: black and white stones on a wooden table by a warm lamp', 'Web · Mobile & desktop', 'Play now', 'Enter the hall'],
  ja: ['連珠館', 'いつでも席に着けるオンライン棋館。三連から七連まで選べる連珠と、黒白の駒を弾いて遊ぶ弾棋を楽しめます。友達を招いて対局したり、3段階の強さのAI「棋魂」と練習したり。ダウンロード不要で、ブラウザからすぐに遊べます。', '連珠館：暖かな灯りと木の卓上の黒白の碁石', 'ブラウザ · スマホ・PC', '公開中', '棋館に入る'],
  ko: ['연주관', '언제든 자리에 앉아 즐기는 온라인 기원. 3목부터 7목까지 규칙을 고르거나, 흑백 말을 튕기는 탄기를 즐겨 보세요. 친구와 대국하거나 세 가지 난이도의 AI 상대인 기혼과 연습할 수 있습니다. 다운로드 없이 브라우저에서 바로 플레이하세요.', '연주관: 따뜻한 등불 아래 나무 탁자에 놓인 흑백 돌', '웹 · 모바일 및 PC', '플레이 가능', '기원 입장'],
  es: ['Lianzhu', 'Toma asiento en una sala de juegos en línea. Elige de tres a siete fichas en raya o juega al Tanqi, impulsando fichas blancas y negras por el tablero. Invita a un amigo o practica contra la IA en tres niveles de dificultad. Juega en el navegador, sin descargar nada.', 'Lianzhu: fichas blancas y negras sobre una mesa de madera junto a una lámpara cálida', 'Web · Móvil y ordenador', 'Disponible', 'Entrar a la sala'],
  fr: ['Lianzhu', 'Prenez place dans une salle de jeu en ligne. Alignez trois à sept pierres, ou jouez au Tanqi en propulsant des pions noirs et blancs sur le plateau. Invitez un ami ou entraînez-vous contre une IA à trois niveaux de difficulté. Jouez dans votre navigateur, sans téléchargement.', 'Lianzhu : pierres noires et blanches sur une table en bois éclairée par une lampe', 'Web · Mobile et ordinateur', 'Disponible', 'Entrer dans la salle'],
  de: ['Lianzhu', 'Nimm Platz in einer Online-Spielhalle. Bringe drei bis sieben Steine in eine Reihe oder schnippe beim Tanqi schwarze und weiße Spielsteine über das Brett. Spiele mit Freunden oder übe gegen die KI in drei Schwierigkeitsstufen. Direkt im Browser, ohne Download.', 'Lianzhu: schwarze und weiße Steine auf einem Holztisch im warmen Lampenlicht', 'Web · Mobil und Desktop', 'Jetzt spielbar', 'Spielhalle betreten'],
  ar: ['ليانتشو', 'اجلس إلى طاولة في قاعة ألعاب عبر الإنترنت. اختر صفًا من ثلاث إلى سبع قطع متصلة، أو العب تانشي بنقر القطع السوداء والبيضاء على اللوح. ادعُ صديقًا للمباراة، أو تدرّب مع خصم بالذكاء الاصطناعي بثلاثة مستويات صعوبة. العب مباشرة في المتصفح دون تنزيل.', 'ليانتشو: قطع سوداء وبيضاء على طاولة خشبية بضوء مصباح دافئ', 'المتصفح · الهاتف والحاسوب', 'متاحة الآن', 'ادخل القاعة'],
}
