export const onCameraCopy = {
  "zh": ["风起敦煌，一人一马入江湖","十年磨一剑 | 汉服 | 武侠 | 敦煌","丝绸古道路漫漫","B站","YouTube","她的名字，始于弓弦惊响","听风无涯，一枕黄粱梦里~~~","上窥青天，下潜黄泉","是九尾狐仙呢！"],
  "zh-Hant": ["風起敦煌，一人一馬入江湖","十年磨一劍 | 漢服 | 武俠 | 敦煌","絲綢古道路漫漫","B站","YouTube","她的名字，始於弓弦驚響","聽風無涯，一枕黃粱夢裡~~~","上窺青天，下潛黃泉","是九尾狐仙呢！"],
  "en": ["Wind Rises in Dunhuang: A Lone Rider Enters the Jianghu","Ten Years to Hone a Sword | Hanfu | Wuxia | Dunhuang","The Long Ancient Silk Road","Bilibili","YouTube","Her Name Begins with the Twang of a Bowstring","Listening to Endless Winds, Lost in a Fleeting Dream…","Gazing into Heaven, Diving into the Underworld","It’s a Nine-Tailed Fox Spirit!"],
  "ja": ["敦煌に風が立つ、一人と一頭で江湖へ","十年かけて一剣を磨く | 漢服 | 武侠 | 敦煌","果てしなく続く古のシルクロード","Bilibiliで見る","YouTubeで見る","彼女の名は、弓弦の鋭い響きから始まる","果てなき風を聴き、ひと枕の黄粱の夢の中へ…","上は青天を窺い、下は黄泉に潜る","九尾の狐仙だよ！"],
  "ko": ["둔황에 바람이 일고, 홀로 말을 타고 강호로","십 년 동안 벼린 검 | 한푸 | 무협 | 둔황","기나긴 옛 실크로드","Bilibili에서 보기","YouTube에서 보기","그녀의 이름은 활시위의 날카로운 울림에서 시작된다","끝없는 바람을 들으며, 베개 위 덧없는 꿈속으로…","위로는 푸른 하늘을 엿보고, 아래로는 황천에 잠기다","구미호 신선이네요!"],
  "es": ["El viento se alza en Dunhuang: a caballo, en solitario, hacia el jianghu","Diez años para forjar una espada | Hanfu | Wuxia | Dunhuang","La larga y antigua Ruta de la Seda","Ver en Bilibili","Ver en YouTube","Su nombre nace del tañido de una cuerda de arco","Escuchando vientos sin fin, en un sueño fugaz…","Contemplar el cielo azul, sumergirse en el inframundo","¡Es un espíritu de zorro de nueve colas!"],
  "fr": ["Le vent se lève à Dunhuang : à cheval, en solitaire, vers le jianghu","Dix ans pour affûter une épée | Hanfu | Wuxia | Dunhuang","La longue et ancienne route de la soie","Voir sur Bilibili","Voir sur YouTube","Son nom naît du claquement d’une corde d’arc","À l’écoute des vents sans fin, dans un rêve éphémère…","Scruter le ciel bleu, plonger aux Sources jaunes","C’est un esprit-renard à neuf queues !"],
  "de": ["Wind über Dunhuang: Allein zu Pferd ins Jianghu","Zehn Jahre, um ein Schwert zu schleifen | Hanfu | Wuxia | Dunhuang","Die lange, alte Seidenstraße","Auf Bilibili ansehen","Auf YouTube ansehen","Ihr Name beginnt mit dem hellen Klang einer Bogensehne","Endlosen Winden lauschen, in einem flüchtigen Traum…","In den blauen Himmel blicken, in die Unterwelt tauchen","Ein neunschwänziger Fuchsgeist!"],
  "ar": ["تهب الرياح في دونهوانغ: فارس وحيد يدخل عالم الجيانغهو","عشر سنوات لصقل سيف | هانفو | ووشيا | دونهوانغ","طريق الحرير القديم الطويل","المشاهدة على Bilibili","المشاهدة على YouTube","يبدأ اسمها برنين وتر القوس المفاجئ","أصغي إلى رياح لا نهاية لها، في حلم عابر…","أتطلع إلى السماء الزرقاء، وأغوص في العالم السفلي","إنها روح ثعلب ذي تسعة ذيول!"],
}
