export const keys = ['books', 'contents', 'start', 'qidian', 'previous', 'next', 'directory', 'browse', 'works', 'author', 'cover', 'illustration', 'loadError', 'retry']
export const copy = {
  zh: ['书籍','目录','开始阅读','起点阅读','上一篇','下一篇','诗集目录','翻阅诗集','篇','光之十一','书封','配图','暂时无法打开书页。','重新打开'],
  'zh-Hant': ['書籍','目錄','開始閱讀','起點閱讀','上一篇','下一篇','詩集目錄','翻閱詩集','篇','光之十一','書封','配圖','暫時無法開啟書頁。','重新開啟'],
  en: ['Books','Contents','Start reading','Read on Qidian','Previous','Next','Collection contents','Browse the collection','poems','Guang Zhi Shiyi','Book cover','Illustration','This book could not be opened.','Try again'],
  ja: ['書籍','目次','読み始める','起点で読む','前の作品','次の作品','詩集の目次','詩集を読む','篇','光之十一','表紙','挿絵','書籍を開けませんでした。','もう一度開く'],
  ko: ['책','목차','읽기 시작','치뎬에서 읽기','이전 작품','다음 작품','시집 목차','시집 둘러보기','편','광지십일','책 표지','삽화','책을 열 수 없습니다.','다시 열기'],
  es: ['Libros','Índice','Empezar a leer','Leer en Qidian','Anterior','Siguiente','Índice del poemario','Recorrer el poemario','poemas','Guang Zhi Shiyi','Cubierta','Ilustración','No se ha podido abrir el libro.','Volver a intentarlo'],
  fr: ['Livres','Sommaire','Commencer la lecture','Lire sur Qidian','Précédent','Suivant','Sommaire du recueil','Parcourir le recueil','poèmes','Guang Zhi Shiyi','Couverture','Illustration','Impossible d’ouvrir ce livre.','Réessayer'],
  de: ['Bücher','Inhalt','Mit dem Lesen beginnen','Auf Qidian lesen','Zurück','Weiter','Inhaltsverzeichnis des Gedichtbands','Im Gedichtband blättern','Gedichte','Guang Zhi Shiyi','Buchcover','Illustration','Das Buch konnte nicht geöffnet werden.','Erneut versuchen'],
  ar: ['الكتب','المحتويات','ابدأ القراءة','اقرأ على تشيديان','السابق','التالي','محتويات المجموعة','تصفّح المجموعة','قصيدة','غوانغ تشي شيي','غلاف الكتاب','صورة توضيحية','تعذّر فتح الكتاب.','حاول مجددًا'],
}
export const descriptions = {
  zh: ['还没取名儿呢','一念凡生','现代诗集','古词牌集','收录2018–2026年的现代诗，写身体、关系、远行，以及变化如何重新塑造一个人。','依新韵十三辙填词，记录行路心迹与当下情思。收录2012–2026年的词作，分为“我本顽痴”与“上下通圆”两卷，附创作日期与释义。','我本顽痴','上下通圆'],
  'zh-Hant': ['還沒取名兒呢','一念凡生','現代詩集','古詞牌集','收錄2018–2026年的現代詩，寫身體、關係、遠行，以及變化如何重新塑造一個人。','依新韻十三轍填詞，記錄行路心跡與當下情思。收錄2012–2026年的詞作，分為「我本頑痴」與「上下通圓」兩卷，附創作日期與釋義。','我本頑痴','上下通圓'],
  en: ['Still Untitled','A Mortal Life, Born of One Thought','Modern poetry','Classical Chinese ci poetry','Poems written between 2018 and 2026 about the body, relationships, journeys, and how change reshapes a person.','Ci poems written between 2012 and 2026, following the thirteen rhyme groups of modern Mandarin. They trace the inner life of a journey and the feelings of the moment, across two volumes: “Stubborn and Foolish by Nature” and “Above and Below, All Connected.” The collection includes writing dates and explanatory notes.','Stubborn and Foolish by Nature','Above and Below, All Connected'],
  ja: ['まだ名前はない','一念凡生','現代詩集','詞牌による詞集','2018–2026年に書かれた現代詩を収録。身体、関係、旅、そして変化が人を新たに形づくる過程を綴る。','現代中国語の新韻十三轍に従って詞を詠み、旅路の心の軌跡とその時々の思いを記した。2012–2026年の作品を「我本頑痴」「上下通円」の二巻に収録し、創作日と解説を添える。','我本頑痴','上下通円'],
  ko: ['아직 이름을 짓지 못했어','한 생각에서 태어난 삶','현대시집','중국 고전 사(詞) 작품집','2018–2026년에 쓴 현대시를 모았다. 몸과 관계, 여정, 그리고 변화가 한 사람을 새롭게 빚어 가는 과정을 쓴다.','현대 중국어의 신운 십삼철에 따라 지은 사(詞)로, 길 위의 마음과 그때그때의 감정을 기록한다. 2012–2026년의 작품을 「본래 고집스럽고 어리석은 나」와 「위아래가 두루 통하다」 두 권으로 나누어 실었으며, 창작 날짜와 해설을 덧붙였다.','본래 고집스럽고 어리석은 나','위아래가 두루 통하다'],
  es: ['Todavía sin título','Una vida mortal nacida de un pensamiento','Poesía moderna','Poesía china clásica ci','Poemas escritos entre 2018 y 2026 sobre el cuerpo, las relaciones, los viajes y cómo los cambios transforman a una persona.','Poemas ci escritos entre 2012 y 2026 según los trece grupos de rimas del mandarín moderno. Recogen el recorrido interior y los sentimientos de cada momento en dos volúmenes: «Obstinada e insensata por naturaleza» y «Arriba y abajo, todo conectado». El poemario incluye fechas de escritura y notas explicativas.','Obstinada e insensata por naturaleza','Arriba y abajo, todo conectado'],
  fr: ['Toujours sans titre','Une vie mortelle née d’une pensée','Poésie moderne','Poésie chinoise classique ci','Des poèmes écrits entre 2018 et 2026 sur le corps, les relations, les voyages et la façon dont le changement transforme une personne.','Des poèmes ci écrits entre 2012 et 2026 selon les treize groupes de rimes du mandarin moderne. Ils retracent un cheminement intérieur et les émotions de l’instant, en deux volumes : « Obstinée et insensée par nature » et « En haut comme en bas, tout est relié ». Le recueil comprend les dates d’écriture et des notes explicatives.','Obstinée et insensée par nature','En haut comme en bas, tout est relié'],
  de: ['Noch ohne Titel','Ein sterbliches Leben, aus einem Gedanken geboren','Moderne Lyrik','Klassische chinesische Ci-Lyrik','Gedichte aus den Jahren 2018–2026 über den Körper, Beziehungen, Reisen und darüber, wie Veränderungen einen Menschen neu formen.','Ci-Gedichte aus den Jahren 2012–2026 nach den dreizehn Reimgruppen des modernen Mandarin. Sie zeichnen einen inneren Weg und die Empfindungen des Augenblicks nach, in zwei Bänden: „Von Natur aus eigensinnig und töricht“ und „Oben und unten, alles verbunden“. Der Band enthält Entstehungsdaten und erläuternde Anmerkungen.','Von Natur aus eigensinnig und töricht','Oben und unten, alles verbunden'],
  ar: ['لم أجد له اسمًا بعد','حياة فانية تولد من فكرة','شعر حديث','شعر تسي الصيني الكلاسيكي','قصائد كُتبت بين عامي 2018 و2026 عن الجسد والعلاقات والترحال، وكيف يعيد التغيّر تشكيل الإنسان.','قصائد تسي كُتبت بين عامي 2012 و2026 وفق مجموعات القافية الثلاث عشرة في الماندرين الحديثة. تسجّل مسيرة النفس ومشاعر اللحظة في مجلدين: «عنيدة وحمقاء بطبعي» و«الأعلى والأسفل، كلٌّ متصل». وتضم المجموعة تواريخ كتابة القصائد وملاحظات تفسيرية.','عنيدة وحمقاء بطبعي','الأعلى والأسفل، كلٌّ متصل'],
}
